var inputstream = [{
    "name": "aquarelle",
    "collection": "apache-oo",
    "tags": "paint,colours,watercolour,red,yellow,rainbow"
  }, {
    "name": "blue-gulls",
    "collection": "apache-oo",
    "tags": "bars"
  }, {
    "name": "dark-fade",
    "collection": "apache-oo",
    "tags": "black,abstract"
  }, {
    "name": "dark-gray-crawls",
    "collection": "apache-oo",
    "tags": "grey,curves,abstract"
  }, {
    "name": "dark-green-curve",
    "collection": "apache-oo",
    "tags": "black,abstract"
  }, {
    "name": "kanagawa",
    "collection": "apache-oo",
    "tags": "painting,wave,water,blue,white,japan"
  }, {
    "name": "oschloe-ballpoint",
    "collection": "apache-oo",
    "tags": "photo,pen,white,stationery"
  }, {
    "name": "oschloe-colored-pencils",
    "collection": "apache-oo",
    "tags": "photo,white,stationery,rainbow"
  }, {
    "name": "oschloe-graph-paper-pencils",
    "collection": "apache-oo",
    "tags": "photo,stationery,rainbow"
  }, {
    "name": "oschloe-phone",
    "collection": "apache-oo",
    "tags": "photo,buttons"
  }, {
    "name": "purple-architecture",
    "collection": "apache-oo",
    "tags": "widescreen,building,photo"
  }, {
    "name": "red-menus",
    "collection": "apache-oo",
    "tags": ""
  }, {
    "name": "sunflowers",
    "collection": "apache-oo",
    "tags": "photo,green,yellow"
  }, {
    "name": "winter-mountains",
    "collection": "apache-oo",
    "tags": "photo,blue,snow"
  }, {
    "name": "xinxinli-black-edges",
    "collection": "apache-oo",
    "tags": "white"
  }, {
    "name": "xinxinli-blue-curves",
    "collection": "apache-oo",
    "tags": ""
  }, {
    "name": "xinxinli-blue-grid",
    "collection": "apache-oo",
    "tags": "lines,geometry"
  }, {
    "name": "xinxinli-blue-squares",
    "collection": "apache-oo",
    "tags": ""
  }, {
    "name": "xinxinli-green-polygons",
    "collection": "apache-oo",
    "tags": ""
  }, {
    "name": "xinxinli-paper-crane",
    "collection": "apache-oo",
    "tags": "blue"
  }, {
    "name": "cinemascope",
    "collection": "chtsai-impress",
    "tags": "widescreen"
  }, {
    "name": "europa",
    "collection": "chtsai-impress",
    "tags": "moon,blue,red,planet,space"
  }, {
    "name": "kaohsiung",
    "collection": "chtsai-impress",
    "tags": "green,trees,taiwan"
  }, {
    "name": "klee1",
    "collection": "chtsai-impress",
    "tags": "green"
  }, {
    "name": "klee2",
    "collection": "chtsai-impress",
    "tags": "blue"
  }, {
    "name": "mars",
    "collection": "chtsai-impress",
    "tags": "dark"
  }, {
    "name": "ooo2",
    "collection": "chtsai-impress",
    "tags": "blue,curves"
  }, {
    "name": "panavision",
    "collection": "chtsai-impress",
    "tags": "widescreen"
  }, {
    "name": "titan",
    "collection": "chtsai-impress",
    "tags": "moon,blue,brown,planet,space"
  }, {
    "name": "tokyo-midtown-1",
    "collection": "chtsai-impress",
    "tags": "photo,japan,street,widescreen"
  }, {
    "name": "tokyo-midtown-2",
    "collection": "chtsai-impress",
    "tags": "photo,japan,mall,bench,people,widescreen"
  }, {
    "name": "tokyo-midtown-3",
    "collection": "chtsai-impress",
    "tags": "photo,japan,building,widescreen"
  }, {
    "name": "widescreen",
    "collection": "chtsai-impress",
    "tags": "blue,clouds,widescreen"
  }, {
    "name": "widescreen-tv",
    "collection": "chtsai-impress",
    "tags": "blue,clouds,widescreen"
  }, {
    "name": "xuhai",
    "collection": "chtsai-impress",
    "tags": "photo,waves,water,blue,sea,surf"
  }, {
    "name": "xuhai2",
    "collection": "chtsai-impress",
    "tags": "photo,waves,water,blue,sea,surf,beach"
  }, {
    "name": "fedora-bubbles",
    "collection": "fedora-slideshow",
    "tags": "blue"
  }, {
    "name": "fedora-clean-blue-white",
    "collection": "fedora-slideshow",
    "tags": ""
  }, {
    "name": "fedora-clean-grey",
    "collection": "fedora-slideshow",
    "tags": "gray"
  }, {
    "name": "fedora-floral-green",
    "collection": "fedora-slideshow",
    "tags": "white,flowers,drawings,curves"
  }, {
    "name": "fedora-gradients-dark",
    "collection": "fedora-slideshow",
    "tags": "blue"
  }, {
    "name": "fedora-gradients-light",
    "collection": "fedora-slideshow",
    "tags": "blue"
  }, {
    "name": "fedora-gradients-medium",
    "collection": "fedora-slideshow",
    "tags": "blue"
  }, {
    "name": "fedora-mirrormanager",
    "collection": "fedora-slideshow",
    "tags": "photo,computer,screen"
  }, {
    "name": "fedora-odometer",
    "collection": "fedora-slideshow",
    "tags": "photo,speed,numbers"
  }, {
    "name": "fedora-patterns-clover",
    "collection": "fedora-slideshow",
    "tags": "dark,grey"
  }, {
    "name": "fedora-patterns-wings",
    "collection": "fedora-slideshow",
    "tags": "light,grey"
  }, {
    "name": "fedora-photography",
    "collection": "fedora-slideshow",
    "tags": "photo,water,droplet"
  }, {
    "name": "fedora-server-theme",
    "collection": "fedora-slideshow",
    "tags": "photo,blue,data"
  }, {
    "name": "fedora-solar-splash",
    "collection": "fedora-slideshow",
    "tags": "blue,flare,planet,space"
  }, {
    "name": "fedora-sunlight-bubbles",
    "collection": "fedora-slideshow",
    "tags": "blue,rays"
  }, {
    "name": "fedora-textures-blue",
    "collection": "fedora-slideshow",
    "tags": "angles"
  }, {
    "name": "fedora-textures-grey-blue",
    "collection": "fedora-slideshow",
    "tags": "gray"
  }, {
    "name": "fedora-textures-wings",
    "collection": "fedora-slideshow",
    "tags": "blue,wave,curves"
  }, {
    "name": "autumn-flowers",
    "collection": "kde-files-org",
    "tags": "brown,drawings"
  }, {
    "name": "braids",
    "collection": "kde-files-org",
    "tags": "white"
  }, {
    "name": "braids-gradient-blue",
    "collection": "kde-files-org",
    "tags": ""
  }, {
    "name": "chalkboard",
    "collection": "kde-files-org",
    "tags": "blackboard,school,skeuomorphic"
  }, {
    "name": "dreaming",
    "collection": "kde-files-org",
    "tags": "blue,drawing,abstract"
  }, {
    "name": "letterpress",
    "collection": "kde-files-org",
    "tags": "serif,typography"
  }, {
    "name": "mazu",
    "collection": "kde-files-org",
    "tags": "photo,red,lanterns,taiwan,kaohsiung"
  }, {
    "name": "red-flowers",
    "collection": "kde-files-org",
    "tags": "drawing,leaves"
  }, {
    "name": "soft-background-brown",
    "collection": "kde-files-org",
    "tags": "gradient,simple"
  }, {
    "name": "soft-background-brown-murky-emboss",
    "collection": "kde-files-org",
    "tags": "gradient,simple"
  }, {
    "name": "soft-background-burgandy",
    "collection": "kde-files-org",
    "tags": "gradient,simple"
  }, {
    "name": "soft-background-green",
    "collection": "kde-files-org",
    "tags": "gradient,simple"
  }, {
    "name": "soft-background-green-emboss",
    "collection": "kde-files-org",
    "tags": "gradient,simple"
  }, {
    "name": "soft-background-sky",
    "collection": "kde-files-org",
    "tags": "gradient,simple"
  }, {
    "name": "spring",
    "collection": "kde-files-org",
    "tags": "green,yellow,leaves,drawings"
  }, {
    "name": "squares",
    "collection": "kde-files-org",
    "tags": "blue"
  }, {
    "name": "traeth-glas",
    "collection": "kde-files-org",
    "tags": "blue,logo,yellow,curves"
  }, {
    "name": "yellow",
    "collection": "kde-files-org",
    "tags": "brown,flowers"
  }, {
    "name": "animal-theme",
    "collection": "lo-cft",
    "tags": "light,cat,tree,elephant,zebra,drawings"
  }, {
    "name": "bright-blue",
    "collection": "lo-cft",
    "tags": "white"
  }, {
    "name": "clean-inspiration",
    "collection": "lo-cft",
    "tags": "light,green"
  }, {
    "name": "cuba-libre",
    "collection": "lo-cft",
    "tags": "orange,drink,recipe,rays,drawing"
  }, {
    "name": "dna",
    "collection": "lo-cft",
    "tags": "white"
  }, {
    "name": "fire-red",
    "collection": "lo-cft",
    "tags": "bar,white"
  }, {
    "name": "four-colors",
    "collection": "lo-cft",
    "tags": "white"
  }, {
    "name": "four-reds",
    "collection": "lo-cft",
    "tags": "white"
  }, {
    "name": "hexagons",
    "collection": "lo-cft",
    "tags": "dark,black,widescreen"
  }, {
    "name": "lush-green",
    "collection": "lo-cft",
    "tags": "white,bar,widescreen"
  }, {
    "name": "metropolis",
    "collection": "lo-cft",
    "tags": "blue,widescreen,rays,drawing,banner,texture,building"
  }, {
    "name": "orange-green",
    "collection": "lo-cft",
    "tags": "bars,puzzle"
  }, {
    "name": "portfolio",
    "collection": "lo-cft",
    "tags": "photo"
  }, {
    "name": "progress",
    "collection": "lo-cft",
    "tags": "grey,angle"
  }, {
    "name": "projections",
    "collection": "lo-cft",
    "tags": "green,light,maps,globe,world"
  }, {
    "name": "red-scribble",
    "collection": "lo-cft",
    "tags": "white,logo"
  }, {
    "name": "scipaper-left",
    "collection": "lo-cft",
    "tags": "green,white,menu"
  }, {
    "name": "scipaper-top",
    "collection": "lo-cft",
    "tags": "green,white"
  }, {
    "name": "simple-blue",
    "collection": "lo-cft",
    "tags": "white"
  }, {
    "name": "smooth-black",
    "collection": "lo-cft",
    "tags": "dark,gradient"
  }, {
    "name": "three-notes",
    "collection": "lo-cft",
    "tags": "skeuomorphic,notepad,grey,sticky,stationery"
  }, {
    "name": "typography-blue",
    "collection": "lo-cft",
    "tags": "gradient,simple"
  }, {
    "name": "typography-gold",
    "collection": "lo-cft",
    "tags": "gradient,simple"
  }, {
    "name": "typography-green",
    "collection": "lo-cft",
    "tags": "gradient,simple"
  }, {
    "name": "typography-purple",
    "collection": "lo-cft",
    "tags": "gradient,simple"
  }, {
    "name": "typography-red",
    "collection": "lo-cft",
    "tags": "gradient,simple"
  }, {
    "name": "lyt-aqua",
    "collection": "lo35-templates",
    "tags": "white"
  }, {
    "name": "lyt-blackandwhite",
    "collection": "lo35-templates",
    "tags": ""
  }, {
    "name": "lyt-bluegrey",
    "collection": "lo35-templates",
    "tags": "gray"
  }, {
    "name": "lyt-bluelinesgrad",
    "collection": "lo35-templates",
    "tags": "gradient"
  }, {
    "name": "lyt-bluetitledown",
    "collection": "lo35-templates",
    "tags": ""
  }, {
    "name": "lyt-book",
    "collection": "lo35-templates",
    "tags": "grey,notebook,skeuomorphic,stationery"
  }, {
    "name": "lyt-brown",
    "collection": "lo35-templates",
    "tags": "curves"
  }, {
    "name": "lyt-charglow",
    "collection": "lo35-templates",
    "tags": "white,letters,type,typography"
  }, {
    "name": "lyt-forest",
    "collection": "lo35-templates",
    "tags": "photo,trees"
  }, {
    "name": "lyt-frepa",
    "collection": "lo35-templates",
    "tags": "grey,abstract,curves"
  }, {
    "name": "lyt-glacier",
    "collection": "lo35-templates",
    "tags": "photo,mountains,snow,blue,white"
  }, {
    "name": "lyt-greengradlines",
    "collection": "lo35-templates",
    "tags": "gradient"
  }, {
    "name": "lyt-keyboard",
    "collection": "lo35-templates",
    "tags": "photo,letters,keys"
  }, {
    "name": "lyt-movwaves",
    "collection": "lo35-templates",
    "tags": "blue,abstract,mauve,curves"
  }, {
    "name": "lyt-numdark",
    "collection": "lo35-templates",
    "tags": "numbers,type,typography"
  }, {
    "name": "lyt-ocean",
    "collection": "lo35-templates",
    "tags": "dark,gradient,black"
  }, {
    "name": "lyt-organic",
    "collection": "lo35-templates",
    "tags": "blue,white"
  }, {
    "name": "lyt-paper",
    "collection": "lo35-templates",
    "tags": "texture,skeuomorphic,white"
  }, {
    "name": "lyt-rededges",
    "collection": "lo35-templates",
    "tags": "light,abstract,curves"
  }, {
    "name": "lyt-roundedrect",
    "collection": "lo35-templates",
    "tags": "rectangles,white,blue"
  }, {
    "name": "lyt-sunrise",
    "collection": "lo35-templates",
    "tags": "orange"
  }, {
    "name": "lyt-techpoly",
    "collection": "lo35-templates",
    "tags": ""
  }, {
    "name": "lyt-tunnel",
    "collection": "lo35-templates",
    "tags": ""
  }, {
    "name": "lyt-water",
    "collection": "lo35-templates",
    "tags": "photo,blue"
  }, {
    "name": "lyt-wine",
    "collection": "lo35-templates",
    "tags": "photo,green,grapes"
  }, {
    "name": "cinema",
    "collection": "lo4-design-candidates",
    "tags": "widescreen,black,white,skeuomorphic"
  }, {
    "name": "fiery",
    "collection": "lo4-design-candidates",
    "tags": "widescreen,light,abstract,fire,trace,orange,brown"
  }, {
    "name": "katana",
    "collection": "lo4-design-candidates",
    "tags": "drawing,sword,japan,scabbard,blade,grey"
  }, {
    "name": "orange-cube",
    "collection": "lo4-design-candidates",
    "tags": "widescreen,grey,logo"
  }, {
    "name": "org-chart-blue",
    "collection": "lo4-design-candidates",
    "tags": "flowchart,organization"
  }, {
    "name": "org-chart-gray",
    "collection": "lo4-design-candidates",
    "tags": "flowchart,organization,grey"
  }, {
    "name": "org-chart-orange",
    "collection": "lo4-design-candidates",
    "tags": "flowchart,organization,gradient"
  }, {
    "name": "pixel",
    "collection": "lo4-design-candidates",
    "tags": "blue"
  }, {
    "name": "round-template",
    "collection": "lo4-design-candidates",
    "tags": "circles,concentric,grey,geometric"
  }, {
    "name": "transversal",
    "collection": "lo4-design-candidates",
    "tags": "angles,green"
  }, {
    "name": "triangle-template",
    "collection": "lo4-design-candidates",
    "tags": "angles,black"
  }, {
    "name": "beehive",
    "collection": "lo5-design-candidates",
    "tags": "skeuomorphic,yellow,honey"
  }, {
    "name": "biei",
    "collection": "lo5-design-candidates",
    "tags": "photo,blue,tree,sky,clouds,grass"
  }, {
    "name": "blue-curve",
    "collection": "lo5-design-candidates",
    "tags": "wave,white"
  }, {
    "name": "classy-red",
    "collection": "lo5-design-candidates",
    "tags": ""
  }, {
    "name": "cosmos",
    "collection": "lo5-design-candidates",
    "tags": "photo,flower,white,pink"
  }, {
    "name": "daruma",
    "collection": "lo5-design-candidates",
    "tags": "white,red,japan,bars"
  }, {
    "name": "drops",
    "collection": "lo5-design-candidates",
    "tags": "photo,water,blue"
  }, {
    "name": "falling-snow",
    "collection": "lo5-design-candidates",
    "tags": "blue"
  }, {
    "name": "forest-bird",
    "collection": "lo5-design-candidates",
    "tags": "green,white,animals,trees,drawing"
  }, {
    "name": "leaf",
    "collection": "lo5-design-candidates",
    "tags": "photo,tree,green"
  }, {
    "name": "lights",
    "collection": "lo5-design-candidates",
    "tags": "gradient,red"
  }, {
    "name": "nature-illustration",
    "collection": "lo5-design-candidates",
    "tags": "drawing,clouds,sun,trees"
  }, {
    "name": "neuron",
    "collection": "lo5-design-candidates",
    "tags": "white,light,abstract"
  }, {
    "name": "notebook",
    "collection": "lo5-design-candidates",
    "tags": "lined,paper,skeuomorphic,white,stationery"
  }, {
    "name": "pencil",
    "collection": "lo5-design-candidates",
    "tags": "writing,white,stationery"
  }, {
    "name": "peter-river",
    "collection": "lo5-design-candidates",
    "tags": "blue,simple"
  }, {
    "name": "piano",
    "collection": "lo5-design-candidates",
    "tags": "keys,black,skeuomorphic"
  }, {
    "name": "sakura",
    "collection": "lo5-design-candidates",
    "tags": "drawing,flowers,pink,white,japan"
  }, {
    "name": "simple-clear",
    "collection": "lo5-design-candidates",
    "tags": "grey"
  }, {
    "name": "simple-dark",
    "collection": "lo5-design-candidates",
    "tags": "black"
  }, {
    "name": "skyblue",
    "collection": "lo5-design-candidates",
    "tags": "gradient,bars"
  }, {
    "name": "star",
    "collection": "lo5-design-candidates",
    "tags": "night,drawing,lights,stars,sky"
  }, {
    "name": "technical-office",
    "collection": "lo5-design-candidates",
    "tags": "stationery,protractor,pencil,eraser,calculator,ruler,white"
  }, {
    "name": "vivid-blue",
    "collection": "lo5-design-candidates",
    "tags": "white"
  }, {
    "name": "alizarin",
    "collection": "lo51-templates",
    "tags": "red,white,bars"
  }, {
    "name": "focus",
    "collection": "lo51-templates",
    "tags": "rainbow,logo,geometry,triangles"
  }, {
    "name": "impress",
    "collection": "lo51-templates",
    "tags": "red,white"
  }, {
    "name": "midnight-blue",
    "collection": "lo51-templates",
    "tags": "green"
  }, {
    "name": "another-poppy",
    "collection": "modern-impress-templates",
    "tags": "orange,curves"
  }, {
    "name": "aquarius",
    "collection": "modern-impress-templates",
    "tags": "blue,curves"
  }, {
    "name": "blue-elegance",
    "collection": "modern-impress-templates",
    "tags": "blue,curves"
  }, {
    "name": "citrus-e",
    "collection": "modern-impress-templates",
    "tags": "green,curves"
  }, {
    "name": "cs3",
    "collection": "modern-impress-templates",
    "tags": "red,orange,curves,gradient"
  }, {
    "name": "cs3mod2",
    "collection": "modern-impress-templates",
    "tags": "yellow,blue,curves,gradient"
  }, {
    "name": "eco-aqua",
    "collection": "modern-impress-templates",
    "tags": "green,curves"
  }, {
    "name": "eco-blue",
    "collection": "modern-impress-templates",
    "tags": "curves"
  }, {
    "name": "eco-cyan",
    "collection": "modern-impress-templates",
    "tags": "curves"
  }, {
    "name": "eco-gold",
    "collection": "modern-impress-templates",
    "tags": "brown,curves"
  }, {
    "name": "eco-green",
    "collection": "modern-impress-templates",
    "tags": "curves"
  }, {
    "name": "eco-grey",
    "collection": "modern-impress-templates",
    "tags": "gray,curves"
  }, {
    "name": "eco-lightblue",
    "collection": "modern-impress-templates",
    "tags": "curves"
  }, {
    "name": "eco-maroon",
    "collection": "modern-impress-templates",
    "tags": "red,curves"
  }, {
    "name": "eco-orange",
    "collection": "modern-impress-templates",
    "tags": "red,curves"
  }, {
    "name": "eco-pink",
    "collection": "modern-impress-templates",
    "tags": "curves"
  }, {
    "name": "eco-purple",
    "collection": "modern-impress-templates",
    "tags": "curves"
  }, {
    "name": "eco-red",
    "collection": "modern-impress-templates",
    "tags": "curves"
  }, {
    "name": "emotion",
    "collection": "modern-impress-templates",
    "tags": "abstract,grey,dark"
  }, {
    "name": "emotion2",
    "collection": "modern-impress-templates",
    "tags": "abstract,blue"
  }, {
    "name": "eos",
    "collection": "modern-impress-templates",
    "tags": "blue,waves,curves,dark"
  }, {
    "name": "fields-of-peace",
    "collection": "modern-impress-templates",
    "tags": "photo,grass,green"
  }, {
    "name": "fresh-morning",
    "collection": "modern-impress-templates",
    "tags": "photo,leaf,water,droplet,green"
  }, {
    "name": "glowing-rectangles",
    "collection": "modern-impress-templates",
    "tags": "black,green,geometry"
  }, {
    "name": "golthia",
    "collection": "modern-impress-templates",
    "tags": "curves,blue"
  }, {
    "name": "green",
    "collection": "modern-impress-templates",
    "tags": "abstract,drawings"
  }, {
    "name": "green-box",
    "collection": "modern-impress-templates",
    "tags": "squares"
  }, {
    "name": "green-concentration",
    "collection": "modern-impress-templates",
    "tags": "rays,lines,angles"
  }, {
    "name": "greenish-wallpaper",
    "collection": "modern-impress-templates",
    "tags": "drawings,abstract"
  }, {
    "name": "lightwave-in-motion",
    "collection": "modern-impress-templates",
    "tags": "curves"
  }, {
    "name": "metal-motion",
    "collection": "modern-impress-templates",
    "tags": "angles,lines,dark"
  }, {
    "name": "moebius-strip",
    "collection": "modern-impress-templates",
    "tags": "dark"
  }, {
    "name": "more-green",
    "collection": "modern-impress-templates",
    "tags": "abstract,green,gradient,rays"
  }, {
    "name": "motion-stripes",
    "collection": "modern-impress-templates",
    "tags": "bars,blue"
  }, {
    "name": "pixels-rock",
    "collection": "modern-impress-templates",
    "tags": "grey,squares"
  }, {
    "name": "sedi",
    "collection": "modern-impress-templates",
    "tags": "orange,curves"
  }, {
    "name": "suse-wallpaper",
    "collection": "modern-impress-templates",
    "tags": "green,curves"
  }, {
    "name": "swamp-gas",
    "collection": "modern-impress-templates",
    "tags": "green,abstract"
  }, {
    "name": "the-bait-nc",
    "collection": "modern-impress-templates",
    "tags": "blue,dark"
  }, {
    "name": "ubuntu-caramel-mocha",
    "collection": "modern-impress-templates",
    "tags": "brown,orange"
  }, {
    "name": "ubuntu-mocha",
    "collection": "modern-impress-templates",
    "tags": "brown,orange"
  }, {
    "name": "globe-blue",
    "collection": "other",
    "tags": "world,map,europe,planet,earth,space"
  }, {
    "name": "shell-blue",
    "collection": "other",
    "tags": "simple"
  }, {
    "name": "shell-red",
    "collection": "other",
    "tags": "white"
  }, {
    "name": "university-lecture",
    "collection": "other",
    "tags": "photo,academic"
  }, {
    "name": "edubuntu-community",
    "collection": "ubuntu-odp",
    "tags": "orange,people,logo"
  }, {
    "name": "edubuntu-escalante",
    "collection": "ubuntu-odp",
    "tags": "orange,logo"
  }, {
    "name": "edubuntu-escondido",
    "collection": "ubuntu-odp",
    "tags": "orange,logo"
  }, {
    "name": "edubuntu-esquipulas",
    "collection": "ubuntu-odp",
    "tags": "orange,logo"
  }, {
    "name": "edubuntu-esteli",
    "collection": "ubuntu-odp",
    "tags": "orange,rays"
  }, {
    "name": "edubuntu-estero-real",
    "collection": "ubuntu-odp",
    "tags": ""
  }, {
    "name": "kubuntu-community",
    "collection": "ubuntu-odp",
    "tags": "blue,gear,people"
  }, {
    "name": "kubuntu-karata",
    "collection": "ubuntu-odp",
    "tags": "blue,gear"
  }, {
    "name": "kubuntu-karawala",
    "collection": "ubuntu-odp",
    "tags": "blue,gear"
  }, {
    "name": "kubuntu-kde-powered",
    "collection": "ubuntu-odp",
    "tags": "blue,gradient"
  }, {
    "name": "kubuntu-kilambe",
    "collection": "ubuntu-odp",
    "tags": "blue,gear"
  }, {
    "name": "kubuntu-kubali",
    "collection": "ubuntu-odp",
    "tags": "blue,gear"
  }, {
    "name": "kubuntu-kukra-hill",
    "collection": "ubuntu-odp",
    "tags": "blue,rays"
  }, {
    "name": "kubuntu-kurinwas",
    "collection": "ubuntu-odp",
    "tags": "blue,gear"
  }, {
    "name": "kubuntu-kurnog",
    "collection": "ubuntu-odp",
    "tags": "blue,gear"
  }, {
    "name": "ubuntu-community",
    "collection": "ubuntu-odp",
    "tags": ""
  }, {
    "name": "ubuntu-curve-brown",
    "collection": "ubuntu-odp",
    "tags": ""
  }, {
    "name": "ubuntu-dots-orange",
    "collection": "ubuntu-odp",
    "tags": "white"
  }, {
    "name": "ubuntu-gnome-powered",
    "collection": "ubuntu-odp",
    "tags": "green,gradient"
  }, {
    "name": "ubuntu-tallship-aubergine",
    "collection": "ubuntu-odp",
    "tags": "purple,sails,sailing,photo"
  }, {
    "name": "ubuntu-ubaldo",
    "collection": "ubuntu-odp",
    "tags": "brown,rays"
  }, {
    "name": "ubuntu-ukapina",
    "collection": "ubuntu-odp",
    "tags": "brown,logo"
  }, {
    "name": "ubuntu-ulang",
    "collection": "ubuntu-odp",
    "tags": "brown,logo"
  }, {
    "name": "ubuntu-uli",
    "collection": "ubuntu-odp",
    "tags": "brown,logo"
  }, {
    "name": "ubuntu-ulwaskin",
    "collection": "ubuntu-odp",
    "tags": "brown,logo"
  }, {
    "name": "ubuntu-umbra",
    "collection": "ubuntu-odp",
    "tags": "orange,logo"
  }, {
    "name": "ubuntu-upa",
    "collection": "ubuntu-odp",
    "tags": "brown,logo"
  }, {
    "name": "ubuntu-world-map-brown",
    "collection": "ubuntu-odp",
    "tags": "earth,geography"
  }, {
    "name": "xubuntu-community",
    "collection": "ubuntu-odp",
    "tags": "people,blue"
  }, {
    "name": "xubuntu-treeline-blue",
    "collection": "ubuntu-odp",
    "tags": "white,subtle"
  }, {
    "name": "xubuntu-xalapa",
    "collection": "ubuntu-odp",
    "tags": "blue,mouse"
  }, {
    "name": "xubuntu-xalteva",
    "collection": "ubuntu-odp",
    "tags": "blue,mouse"
  }, {
    "name": "xubuntu-xiloa",
    "collection": "ubuntu-odp",
    "tags": "blue,rays"
  }, {
    "name": "xubuntu-xilonem",
    "collection": "ubuntu-odp",
    "tags": "blue,mouse"
  }, {
    "name": "xubuntu-xolotlan",
    "collection": "ubuntu-odp",
    "tags": "blue,mouse"
  }, {
    "name": "material-blue",
    "collection": "user-contrib/material-simple",
    "tags": ""
  }, {
    "name": "material-brown",
    "collection": "user-contrib/material-simple",
    "tags": ""
  }, {
    "name": "material-green",
    "collection": "user-contrib/material-simple",
    "tags": ""
  }, {
    "name": "material-grey",
    "collection": "user-contrib/material-simple",
    "tags": "gray"
  }, {
    "name": "material-lime",
    "collection": "user-contrib/material-simple",
    "tags": ""
  }, {
    "name": "material-orange",
    "collection": "user-contrib/material-simple",
    "tags": ""
  }, {
    "name": "material-pink",
    "collection": "user-contrib/material-simple",
    "tags": ""
  }, {
    "name": "material-purple",
    "collection": "user-contrib/material-simple",
    "tags": ""
  }, {
    "name": "material-red",
    "collection": "user-contrib/material-simple",
    "tags": ""
  }, {
    "name": "material-teal",
    "collection": "user-contrib/material-simple",
    "tags": ""
  }, {
    "name": "material-yellow",
    "collection": "user-contrib/material-simple",
    "tags": ""
}];
